name: Reusable workflow example

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string


jobs:
  cat-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - id: catfile
      run: | 
         cat ${{ inputs.filename }}
