name: successful-workflow

on: 
  workflow_dispatch:
  
jobs:
  successfuljob:
   runs-on: ubuntu-latest
   steps:
        
   - name: Checkout   
     uses: actions/checkout@v4
        
   - id: date
     run: |
       tar cvzf ValidationArtifact.tgz README.md 

   - name: upload artifact
     uses: actions/upload-artifact@v4
     with:
          name: ValidationArtifact
          path: ValidationArtifact.tgz
