name: successful-workflow

on: 
  workflow_dispatch:
  
jobs:
  successfuljob:
   runs-on: ubuntu-latest
   steps:
        
   - name: Checkout   
     uses: actions/checkout@v3.2.0
        
   - id: date
     run: |
       tar cvf ValidationArtifact.tgz README.md 

   - name: upload artifact
     uses: actions/upload-artifact@v3
     with:
          name: ValidationArtifact
          path: ValidationArtifact.tgz
