name: Trigger-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  run-trigger-tests:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
          
      - name: Notify teams Linux
        if: always()
        run: .github/bin/notify-result-teams.sh
        env:
        
          VALIDATION_PART: 'TRIGGER'
          VALIDATION_STATUS: '${{ job.status }}'
          VALIDATION_OS: '${{github.event_name}}' 
          TEAMS_WEBHOOK: '${{ secrets.TEAMS_WEBHOOK }}'    

      - name: Notify slack Linux
        if: always()
        run: .github/bin/notify-result-slack.sh
        env:
        
          VALIDATION_PART: 'TRIGGER'
          VALIDATION_STATUS: '${{ job.status }}'
          VALIDATION_OS: '${{github.event_name}}' 
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'     
