name: Trigger-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:

  getvars:
   runs-on: ubuntu-latest
   outputs:
     ghdate: ${{ steps.date.outputs.date }} 
     ghbranch: ${{ steps.extractbranch.outputs.branch }} 
   steps:
   - id: date
     run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
   - id: extractbranch
     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

        
  run-trigger-tests:
   runs-on: ubuntu-latest
   needs: getvars
   steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Notify teams Linux
        if: always()
        run: .github/bin/notify-result-teams.sh
        env:
        
          VALIDATION_PART: 'TRIGGER'
          VALIDATION_STATUS: 'success'
          VALIDATION_OS: '${{github.event_name}}' 
          TEAMS_WEBHOOK: '${{ secrets.TEAMS_WEBHOOK }}'    

      - name: Notify slack Linux
        if: always()
        run: .github/bin/notify-result-slack.sh
        env:
        
          VALIDATION_PART: 'TRIGGER'
          VALIDATION_STATUS: 'success'
          VALIDATION_OS: '${{github.event_name}}' 
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'     
        
